insert into text(id, title, total_pages) values (1, 'La llamada de la selva', 3);
insert into text(id, title, total_pages) values (2, 'Cinco semanas en globo', 5);
insert into text(id, title, total_pages) values (3, 'Ya no viajo en moto', 1);

insert into page (text_id, page_number, text) values (1,1,'Buck no leía los periódicos, de lo contrario habría sabido que una amenaza se cernía no sólo sobre él, sino sobre cualquier otro perro de la costa, entre Puget Sound y San Diego, con fuerte musculatura y largo y abrigado pelaje. Porque a tientas, en la oscuridad del Ártico, unos hombres habían encontrado un metal amarillo y, debido a que las compañías navieras y de transporte propagaron el hallazgo, miles de otros hombres se lanzaban hacia el norte. Estos hombres necesitaban perros, y los querían recios, con una fuerte musculatura que los hiciera resistentes al trabajo duro y un pelo abundante que los protegiera del frío.
Buck vivía en una extensa propiedad del soleado valle de Santa Clara, conocida como la finca del juez Miller. La casa estaba apartada de la carretera, semioculta entre los árboles a través de los cuales se podía vislumbrar la ancha y fresca galería que la rodeaba por los cuatro costados. Se llegaba a ella por senderos de grava que serpenteaban entre amplios espacios cubiertos de césped y bajo las ramas entrelazadas de altos álamos. En la parte trasera las cosas adquirían proporciones todavía más vastas que en la delantera.');
insert into page (text_id, page_number, text) values (1,2,'Había espaciosas caballerizas atendidas por una docena de cuidadores y mozos de cuadra, hileras de casitas con su enredadera para el personal, una larga y ordenada fila de letrinas, extensas pérgolas emparradas, verdes prados, huertos y bancales de fresas y frambuesas');
insert into page (text_id, page_number, text) values (1,3,'Después de un golpe especialmente feroz, sus patas vacilaron y quedó demasiado aturdido para atacar. Se tambaleó sin fuerzas, con sangre manándole de la nariz, la boca y las orejas, con el hermoso pelaje salpicado y con manchas de saliva ensangrentada. Entonces el hombre avanzó y deliberadamente le asestó un espantoso golpe en el hocico. Todo el dolor que había soportado Buck no fue nada en comparación con la intensa agonía de éste. Con un rugido de ferocidad casi leonina, volvió a lanzarse contra el hombre. Pero el hombre, pasándose el garrote de la derecha a la izquierda, cogió diestramente a Buck por debajo del maxilar inferior, dando al mismo tiempo un tirón hacia abajo y hacia atrás. Buck describió un círculo completo en el aire, para después golpear el suelo con la cabeza y el pecho.
Atacó por última vez. El hombre descargó entonces el golpe que le había reservando durante toda la lucha y Buck se derrumbó y cayó al suelo sin sentido.');

insert into page (text_id, page_number, text) values (2,1,'Así pues, el doctor era hombre bien conocido, pese a no pertenecer a ninguna institución científica, ni a las Reales Sociedades Geográficas de Londres, París, Berlín, Viena o San Petersburgo, ni al Club de los Viajeros, ni siquiera a la Royal Politechnic Institution, donde su amigo, el estadista Kokburn, metía mucho ruido. Un día Kokburn le propuso, para darle gusto, resolver el siguiente problema: dado el número de millas recorridas por el doctor alrededor del mundo, cuántas millas más ha andado su cabeza que sus pies, teniendo en cuenta la diferencia de los radios O bien, conociendo el número de millas recorridas por los pies y por la cabeza del doctor, calcular su estatura con toda exactitud.');
insert into page (text_id, page_number, text) values (2,2,'Dick Kennedy era escocés en toda la aceptación de la palabra franco, resuelto y obstinado. Vivía en la aldea de Leith, cerca de Edimburgo, un verdadero arrabal de la -Vieja Ahumada-. A veces practicaba la pesca, pero en todas partes y siempre era un cazador determinado, lo que nada tiene de particular en un hijo de Caledonia algo aficionado a recorrer las montañas de Highlands. Se le citaba como un maravilloso tirador de escopeta, pues no sólo partía las balas contra la hoja de un cuchillo, sino que las partía en dos mitades tan iguales que, pesándolas luego, no se hallaba entre una y otra diferencia apreciable.');
insert into page (text_id, page_number, text) values (2,3,'Los dos amigos se conocieron en la India, donde servían en un mismo regimiento. Mientras Dick cazaba tigres y elefantes, Samuel cazaba plantas e insectos. Cada cual podía blasonar de diestro en su especialidad, y más de una planta rara cogió el doctor, cuya conquista le costó tanto como un buen par de colmillos de marfil. Los dos jóvenes nunca tuvieron ocasión de salvarse la vida uno a otro ni de prestarse servicio alguno, por lo que su amistad permanecía inalterable. Algunas veces les alejó la suerte, pero siempre les volvió a unir la simpatía.');
insert into page (text_id, page_number, text) values (2,4,'Después de su viaje al Tibet, el doctor estuvo dos años sin hablar de expediciones nuevas. Dick llegó a imaginar que se habían apaciguado los instintos de viaje e impulsos aventureros de su amigo, lo que le complacía en extremo. La cosa, se decía a sí mismo, tenía un día u otro que concluir de mala manera. Por más que se tenga don de gentes, no se viaja impunemente entre antropófagos y fieras. Kennedy procuraba, pues, tener a raya a Samuel, que había hecho ya bastante por la ciencia y demasiado para la gratitud humana. El doctor no respondía una palabra; permanecía pensativo y después se entregaba a secretos cálculos, pasando las noches en operaciones de números y experimentos con aparatos singulares de los que nadie se percataba. Se percibía que en su cerebro fermentaba un gran pensamiento.');
insert into page (text_id, page_number, text) values (2,5,'La línea aérea que el doctor Fergusson se proponía seguir no había sido escogida al azar; su punto de partida fue cuidadosamente estudiado, y no sin razón el explorador resolvió verificar la ascensión desde la isla de Zanzíbar. Esta isla, situada cerca de la costa oriental de África, se encuentra a 60 de latitud austral, es decir, cuatrocientas treinta millas geográficas debajo del ecuador. De aquella isla acababa de partir la última expedición enviada por los Grandes Lagos en busca del nacimiento del Nilo.');

insert into page (text_id, page_number, text) values (3,1,'Ayer yo iba en mi moto cuando me sacudió un terremoto, de mi moto casi azoté por culpa de ese terremoto, y yo en mi moto moviéndome por ese terremoto. Ya no viajo en mi moto porque me espantó ese terremoto.');

